<a href="https://colab.research.google.com/github/tajain07/neural-network-playground/blob/master/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

X = X/np.amax(X, axis=0)
y = y/100

In [37]:
class Neural_Network(object):
  def __init__(self):
    self.input_size = 2
    self.output_size = 1
    self.hidden_size = 3
    
    self.input_to_hidden = np.random.randn(self.input_size, self.hidden_size)
    self.hidden_to_output = np.random.randn(self.hidden_size, self.output_size)
  
  def sigmoid(self, s):
    # activation function 
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)
  
  
  def forward(self, X):
    self.hidden_input = np.dot(X, self.input_to_hidden)
    self.hidden_output = self.sigmoid(self.hidden_input)
    
    self.final_input = np.dot(self.hidden_output, self.hidden_to_output)
    self.final_ouput = self.sigmoid(self.final_input)
    
    return self.final_ouput
  
  def backward(self, X, y, o):
    
    self.output_error = y - o
    self.output_delta = self.output_error*self.sigmoidPrime(o)
    
    self.hidden_error = self.output_delta.dot(self.hidden_to_output.T)
    self.hidden_delta = self.hidden_error*self.sigmoidPrime(self.hidden_output)
    
    self.input_to_hidden += X.T.dot(self.hidden_delta)
    self.hidden_to_output += self.hidden_output.T.dot(self.output_delta)
    
    
  def train (self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)
    
    
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  if(i%10 == 0):
    print("Input: \n" + str(X)) 
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
    print("\n")
  NN.train(X, y)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.16655403]
 [0.18501369]
 [0.23007387]]
Loss: 
0.4862632791909338


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.79381445]
 [0.7525442 ]
 [0.75460328]]
Loss: 
0.015267271198970896


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.86510472]
 [0.82707445]
 [0.82451007]]
Loss: 
0.0027955050419504273


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88685226]
 [0.8510297 ]
 [0.84793816]]
Loss: 
0.0009828124911663697


Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predict